### ISSUE TITLE
Returning list of trained models.

### ISSUE THREAD

**Issue by washcycle** [nikita-moor/ldatuning#2]
I was thinking it might be a good idea to return a list of models instead of a data.frame of the metric. Similar to how the `caret` package tunes models.

My current usage right now is to run the model which takes a long time, then I have to run it again on the desired number of topics. If it could cache the models that would be great or at least have a parameter to turn that feature on and off.

What do you think?

**Comment by plablo09** [comment]
I think this is a recurrent use case so I made a very simple implementation that stores the fitted models along with ldatuning result in a named list. My fork with the implementation is [here](https://github.com/CentroGeo/ldatuning) if someone wants to use it right away. @nikita-moor Do you feel like this is something useful for this package?

**Comment by nikita-moor** [comment]
Thank you for your contribution, @plablo09. I will check the code later, but can't promise fast response, this project is not very active though.

The main cause why I don't like this proposal is the way many people understand meaning of the "optimal number of topics". If a method says, for example, that the optimal `k` is 112 or 238, it does not mean these values should be used. LDA is not a deterministic method, so `k` could be defined with great tolerance, such as 250 instead of 238.

Working with real-size corpora one cannot check every value of `k` but roughly outline shape of the plot and then choose more or less appropriate value. So, I was never in situation, when the exactly best model is in the list and could be returned.

Anyway, I will review your code.

**Comment by plablo09** [comment]
I certainly see your point @nikita-moor. I think storing the fitted models is useful for a number of reasons and not just for extracting the _best_ model from the list. For example, it is common to compare model performance across a wide range of `k` values while at the same time getting an approximate idea of the _optimal_ `k`. In these type of scenarios, having the whole fitted models list available is very useful.

**Comment by titaniumtroop** [comment]
I added pull request #15 for returning models. It requires the tibble package. I also added a demo that prints a tibble with the return_models flag set to true to show how the values are returned.

If the tibble package is not present, a message prints stating that the tibble package is required. Only the results are returned in that case.
