### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by mvingar** [nikita-moor/ldatuning#9]
Delete

**Comment by nikita-moor** [comment]
Your code should work fine with this parameters:

`tuning.controlGibbs <- list(burnin = 2500, iter = 5000, seed = 3411)`

Pay attention to `burnin` (in place of "burning"). Parameter `best` is useless because `FindTopicsNumber` does not return the model, but metrics values only.

I am not sure what does `nstart` should do, but it does not work with direct call to `topicmodels` function, so it is out of my code. This code returns an error:
~~~
library("ldatuning")
library("topicmodels")
data("AssociatedPress", package="topicmodels")
dtm <- AssociatedPress[1:10, ]

topicmodels::LDA(
  dtm,
  k = 10,
  method = method,
  control = list(burnin = 2500, iter = 5000, seed = 3411)
)
~~~

I recommend you to check parameters on the last code firstly (you can change `dtm` matrix to yours) and then apply them to `FindTopicsNumber`.

**Comment by nikita-moor** [comment]
Could I close the issue?

**Comment by mvingar** [comment]
Yup, go ahead and delete it if you want!
